name: Documentation

on:
  push:
    branches:
      - master
      - maint/*
      - rel/*
      - docs/*
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.9
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pybids
        run: pip install .[doc]
      - name: Build documentation
        run: make -C doc html
      - name: Upload docs as artifacts
        uses: actions/upload-artifact@v3
        with:
            path: doc/_build/html
      - name: Deploy (on tags)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: doc/_build/html
            force_orphan: true
            user_name: "BIDS Maintenance"
            user_email: bids-maintenance@gmail.com
